import 'dart:async';

import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:tahsel/features/my_debts/domain/entities/my_debt_item_entity.dart';
import 'package:tahsel/features/my_debts/domain/entities/my_debt_person_entity.dart';
import 'package:tahsel/features/my_debts/domain/usecases/debt/add_my_debt_usecase.dart';
import 'package:tahsel/features/my_debts/domain/usecases/payment/distribute_my_debt_payment_usecase.dart';
import 'package:tahsel/features/my_debts/domain/usecases/person/get_my_debt_persons_usecase.dart';
import 'package:tahsel/features/my_debts/domain/usecases/person/update_my_debt_person_preference_usecase.dart';
import 'package:tahsel/features/my_debts/presentation/cubit/my_debts_state.dart';

class MyDebtsCubit extends Cubit<MyDebtsState> {
  final GetMyDebtPersonsUseCase getPersonsUseCase;
  final AddMyDebtUseCase addDebtUseCase;
  final DistributeMyDebtPaymentUseCase distributePaymentUseCase;
  final UpdateMyDebtPersonPreferenceUseCase updatePreferenceUseCase;

  MyDebtsCubit({
    required this.getPersonsUseCase,
    required this.addDebtUseCase,
    required this.distributePaymentUseCase,
    required this.updatePreferenceUseCase,
  }) : super(const MyDebtsState());

  List<MyDebtPersonEntity> _allPersons = [];
  Timer? _searchDebounce;

  Future<void> loadPersons(String uid, {bool forceRefresh = false}) async {
    if (isClosed) return;
    if (!forceRefresh &&
        state.status == MyDebtsStatus.loaded &&
        state.persons.isNotEmpty) {
      return;
    }

    emit(state.copyWith(status: MyDebtsStatus.loading, clearMessage: true));

    final result = await getPersonsUseCase(uid);
    if (isClosed) return;
    result.fold(
      (failure) => emit(
        state.copyWith(status: MyDebtsStatus.error, message: failure.message),
      ),
      (persons) {
        _allPersons = persons;
        _emitLoaded(persons);
      },
    );
  }

  void _emitLoaded(List<MyDebtPersonEntity> persons) {
    double totalOwed = 0;
    double totalPaid = 0;
    for (var p in persons) {
      totalOwed += p.totalRemainingDebt;
      totalPaid += (p.totalDebtAmount - p.totalRemainingDebt);
    }

    emit(
      state.copyWith(
        status: MyDebtsStatus.loaded,
        persons: persons,
        filteredPersons: persons,
        totalOwed: totalOwed,
        totalPaid: totalPaid,
        totalPeople: persons.length,
      ),
    );
  }

  Future<void> addDebt({
    required String uid,
    required String personName,
    required double totalAmount,
    required double paidAmount,
    String? details,
    String? phone,
  }) async {
    // if (isClosed) return;
    emit(
      state.copyWith(
        status: MyDebtsStatus.addingDebt,
        processingId: personName,
      ),
    );

    final now = DateTime.now();
    final debt = MyDebtItemEntity(
      id: '', // Generated by server
      uid: uid,
      operationId: 'manual_my_debt_${now.millisecondsSinceEpoch}',
      totalAmount: totalAmount,
      paidAmount: paidAmount,
      remainingAmount: totalAmount - paidAmount,
      personName: personName,
      details: details ?? 'ديون جديدة',
      operationType: 'debt',
      timestamp: now,
      isPaid: (totalAmount - paidAmount) <= 0,
      phoneNumber: phone,
    );

    final result = await addDebtUseCase(debt);
    if (isClosed) return;
    result.fold(
      (failure) => emit(
        state.copyWith(status: MyDebtsStatus.error, message: failure.message),
      ),
      (_) => loadPersons(uid, forceRefresh: true),
    );
  }

  Future<void> payTotalDebt({
    required String uid,
    required String personName,
    required double amount,
    required double totalRemainingBefore,
  }) async {
    if (isClosed) return;
    emit(
      state.copyWith(
        status: MyDebtsStatus.addingPayment,
        processingId: personName,
      ),
    );

    final result = await distributePaymentUseCase(
      uid: uid,
      personName: personName,
      amount: amount,
    );

    if (isClosed) return;
    result.fold(
      (failure) => emit(
        state.copyWith(status: MyDebtsStatus.error, message: failure.message),
      ),
      (_) {
        emit(
          state.copyWith(
            status: MyDebtsStatus.loaded,
            lastPaymentPerson: personName,
            lastPaymentAmount: amount,
            lastPaymentRemaining: totalRemainingBefore - amount,
          ),
        );
        loadPersons(uid, forceRefresh: true);
      },
    );
  }

  Future<void> updatePreference(
    String uid,
    String name,
    String preference,
  ) async {
    // Optimistic Update
    final updated = _allPersons.map((p) {
      if (p.name == name) return p.copyWith(notificationPreference: preference);
      return p;
    }).toList();
    _emitLoaded(updated);

    final result = await updatePreferenceUseCase(uid, name, preference);
    result.fold(
      (failure) => loadPersons(uid, forceRefresh: true), // Rollback
      (_) => null,
    );
  }

  void search(String query) {
    if (_searchDebounce?.isActive ?? false) _searchDebounce!.cancel();
    _searchDebounce = Timer(const Duration(milliseconds: 500), () {
      if (isClosed) return;
      final filtered = query.isEmpty
          ? _allPersons
          : _allPersons
                .where(
                  (p) => p.name.toLowerCase().contains(query.toLowerCase()),
                )
                .toList();
      _emitLoaded(filtered);
    });
  }

  void clearFlags() {
    if (isClosed) return;
    emit(
      state.copyWith(
        clearMessage: true,
        clearLastPayment: true,
        clearProcessingId: true,
      ),
    );
  }

  @override
  Future<void> close() {
    _searchDebounce?.cancel();
    return super.close();
  }
}
